### ISSUE TITLE
its only using cpu, vram and gpu are not used at all.

### ISSUE THREAD

**Issue by shivdbz2010** [squirrel765/ComfyUI-LLM-VLM-Node#2]
its only using cpu, vram and gpu are not used at all.

**Comment by shivshankar11** [comment]
THIS FIXED IT
$env:CMAKE_ARGS="-DGGML_CUDA=on"
$env:CUDA_CXX="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin\nvcc.exe"
pip install llama-cpp-python  --no-cache-dir
